// /**
import {isMatchKeymapPattern} from "../src/deep_same";

console.log(isMatchKeymapPattern('a.**.x.**.j*j', 'a')===true)
console.log(isMatchKeymapPattern('a.**.x.**.j*j', 'a')===true)
console.log(isMatchKeymapPattern('a.**.x.**.j*j', 'a')===true)
console.log(isMatchKeymapPattern('a.**.x.**.j*j', 'a')===true)
console.log(isMatchKeymapPattern('a.**.x.**.j*j', 'a')===true)
console.log(isMatchKeymapPattern('a.**.x.**.j*j', 'a')===true)
console.log(isMatchKeymapPattern('a.**.x.**.j*j', 'a')===true)
console.log(isMatchKeymapPattern('a', 'a.b')===true)
console.log(isMatchKeymapPattern('**', 'a')===true)
console.log(isMatchKeymapPattern('**', 'a.b')===true)
console.log(isMatchKeymapPattern('**', 'a.b.c')===true)
console.log(isMatchKeymapPattern('a.**', 'a')===true)
console.log(isMatchKeymapPattern('a.**', 'a.b')===true)
console.log(isMatchKeymapPattern('a.**', 'a.b.c')===true)
console.log(isMatchKeymapPattern('a.**.b', 'a')===true)
console.log(isMatchKeymapPattern('a.**.b', 'a.b')===true)
console.log(isMatchKeymapPattern('a.**.b', 'b.a.b')===false)
console.log(isMatchKeymapPattern('a.**.b', 'a.b.c')===true)
console.log(isMatchKeymapPattern('a.**.b', 'a.c.b')===true)
console.log(isMatchKeymapPattern('*', '')===true)
console.log(isMatchKeymapPattern('*', 'a')===true)
console.log(isMatchKeymapPattern('*', 'a.b')===true)
console.log(isMatchKeymapPattern('*', 'a.b.c')===true)
// console.log(isMatchKeymapPattern('a.*', 'a')===false)
console.log(isMatchKeymapPattern('a.*', 'a')===true)
console.log(isMatchKeymapPattern('a.*', 'a.')===true)
console.log(isMatchKeymapPattern('a.*', 'b.')===false)
console.log(isMatchKeymapPattern('a.*', 'a.b')===true)
console.log(isMatchKeymapPattern('a.*', 'a.b.c')===true)
console.log(isMatchKeymapPattern('a.*.z', 'a')===true)
console.log(isMatchKeymapPattern('a.*.z', 'a.b')===true)
console.log(isMatchKeymapPattern('a.*.z', 'a.z')===true)
console.log(isMatchKeymapPattern('a.*.z', 'a.b.z')===true)
// */